### ISSUE TITLE
Unset user permissions are added to the permissions

### ISSUE THREAD

**Issue by Al-Demon** [david-szabo97/grav-plugin-admin-addon-user-manager#38]
Please I don't know what I'm doing wrong...

I create a group call editor with this permissions:
```yaml
editor:
  groupname: editor
  readableName: editor
  description: writer
  access:
    admin:
      login: 'true'
      pages: 'true'
    admin-addon-user-manager: {  }
    site: {  }
```
And I have a new user:
```yaml
groups:
  - editor
access:
  admin:
    super: ''
    login: ''
    cache: ''
    configuration: ''
    configuration_system: ''
    configuration_site: ''
    configuration_media: ''
    configuration_info: ''
    settings: ''
    pages: ''
    maintenance: ''
    statistics: ''
    plugins: ''
    themes: ''
    users: ''
  admin-addon-user-manager:
    users: ''
    groups: ''
    users_expert: ''
  site:
    login: ''
```
_ _ _

And I can't login... only if I configured the user admin login true... but I could do this before without the plugin... I think this plugin is for create group, not for configure each user, right?

Thanks for all
