### ISSUE TITLE
User "enabled" value set incorrectly, cannot log in with panel-created users.

### ISSUE THREAD

**Issue by Quark11** [david-szabo97/grav-plugin-admin-addon-user-manager#42]
When a new user is created via the user-manager admin panel, the `state` value in the corresponding account yaml file is surrounded by extra pairs of quotes. For example instead of `state: enabled`, it shows `state: '"enabled"'. This  prevents users created in this way from logging in. If you try logging into that user's account via the "Login as" button, an exception will be thrown.

Manually editing the user's account yaml file to change the state value to `enabled` without the quotes allows the account to work as expected.

**Comment by david-szabo97** [comment]
I have just updated everything. And I can login with a freshly created user.

This is the generated YAML and it works fine.
```yaml
state: enabled
_json:
  avatar: 'null'
  state: '"enabled"'
  hashed_password: '"$2y$10$zNNKpkhJsTSA4ns2xSwVzuxwgGhMS1xBS4X7xYzfTKPmMguKviQtu"'
email: testlogin@testlogin.com
fullname: 'test test'
language: en
twofa_enabled: false
twofa_secret: GC5BC7GQWIQNUZWXLBQUU73YGLBLIFNL
access:
  site:
    login: 'true'
  admin:
    login: 'true'
  admin-addon-user-manager: {  }
  users: {  }
hashed_password: $2y$10$zNNKpkhJsTSA4ns2xSwVzuxwgGhMS1xBS4X7xYzfTKPmMguKviQtu
```
