### ISSUE TITLE
Saving a group adds a related ghost group

### ISSUE THREAD

**Issue by benjarmin** [david-szabo97/grav-plugin-admin-addon-user-manager#59]
Saving a group does not correctly reference the group name in the /user/config/groups.yaml file and instead creates a duplicate ghost group. Issue applies to saving new groups and existing groups.

**Environment**

Admin Addon User Manager v2.1.6
Admin Panel v1.9.4
Grav 1.6.9
PHP 7.2.17

**Reproduce**

1. Add/Edit group from groups manager
2. Save group
3. Group attributes and permissions do not render back although are saved
4. groups.yaml now holds a duplicate group but with empty reference to group name
5. Duplicate group appears in the groups list in the plugin but fails to open config page
6. Editing the original group saves attributes and permissions into the duplicate group
7. Editing a different group replaces the group with no name with the new attributes and permissions

**Workaround**

Edit groups.yaml directly

**Groups File**

groups.yaml file after saving an edit to an existing distributors group:

distributors:
  readableName: Distributors
  description: 'A group for distributors'
  access:
    site:
      login: 'true'
    admin: {  }
    admin-addon-user-manager: {  }
'':
  readableName: Distributors
  description: 'An edit to the group for distributors'
  access:
    site:
      login: 'true'
    admin: {  }
    admin-addon-user-manager: {  }

**Comment by boutmos** [comment]
Hi,
I have the same issue. From the backend, when I add a group, It override, the latest group created with a ''.

# Environment

Admin Addon User Manager v2.1.7
Admin Panel v1.9.4
Grav 1.6.9
PHP 7.3.5
Nginx 1.10

# Groups File :

```
adminsys:
  readableName: adminsys
  access:
    site: {  }
    admin: {  }
    admin-addon-user-manager: {  }
exterieur:
  readableName: exterieur
  access:
    site: {  }
    admin: {  }
    admin-addon-user-manager: {  }
enseignant:
  readableName: enseignant
  access:
    site: {  }
    admin: {  }
    admin-addon-user-manager: {  }
```

Groups file after a creation from backend : 
```
adminsys:
  readableName: adminsys
  access:
    site: {  }
    admin: {  }
    admin-addon-user-manager: {  }
exterieur:
  readableName: exterieur
  access:
    site: {  }
    admin: {  }
    admin-addon-user-manager: {  }
enseignant:
  readableName: enseignant
  access:
    site: {  }
    admin: {  }
    admin-addon-user-manager: {  }
'':
  readableName: etudiant
  description: 'Group for etudiant'
  access:
    site: {  }
    admin: {  }
    admin-addon-user-manager: {  }
```
Then groups file after another creation :

```
  readableName: adminsys
  access:
    site: {  }
    admin: {  }
    admin-addon-user-manager: {  }
exterieur:
  readableName: exterieur
  access:
    site: {  }
    admin: {  }
    admin-addon-user-manager: {  }
enseignant:
  readableName: enseignant
  access:
    site: {  }
    admin: {  }
    admin-addon-user-manager: {  }
'':
  readableName: secretaire
  description: 'Groupe pour les secrétaires administratifs et pedagogique'
  access:
    site: {  }
    admin: {  }
    admin-addon-user-manager: {  }
```
