### ISSUE TITLE
Add configuration option for disabling Groups Manager

### ISSUE THREAD

**Issue by zouloux** [david-szabo97/grav-plugin-admin-addon-user-manager#70]
Hi, thanks for this useful plugin :-) 
I wanted to add a feature to remove groups from Grav Admin menu. I do not use this feature on all of my projects, this may be interesting for other people who want the cleanest admin possible.

Added this condition into `admin-addon-user-manager.php` line 60
```
if ($this->getPluginConfigValue('enable_groups', 1))
    	$this->managers[] = new GroupsManager($this->grav, $this);
```

Also the option at the bottom of `blueprints.yaml` : 
```
    enable_groups:
      type: toggle
      label: "Enable groups"
      default: 1
      highlight: 1
      options:
        1: PLUGIN_ADMIN.ENABLED
        0: PLUGIN_ADMIN.DISABLED
```

We just miss the `label` translation in all languages. Tell me if I can do a PR. Thanks !
