### ISSUE TITLE
Extending group blueprints

### ISSUE THREAD

**Issue by masetto** [david-szabo97/grav-plugin-admin-addon-user-manager#72]
Hello,
I tried to extend group blueprint to add a field, but I couldn't. As for user blueprint I created a file named `user/blueprints/group.yaml` with this content:
```
extends@:
    type: user/group
    context: blueprints://

form:
    fields:
        root_page:
            ordering@: description
            label: Main group page
            type: text
            validate:
                required: false
```

but when I edit a group in admin I don't see any change.
Please, how do I do this?

**Comment by david-szabo97** [comment]
Hi @masetto ! Please only post requests/issues related to the Admin Addon User Manager plugin here. You will have better luck asking the question on the [Grav's Forum](https://discourse.getgrav.org/).

**Comment by masetto** [comment]
Hi @david-szabo97. Sorry, but in my opinion this is a specific question about this plugin: I not be able to extend group blueprint, while for users I created a yaml named `accounts.yaml` as this:
```
extends@:
    type: user/account
    context: blueprints://

form:
    fields:
        title:
            unset@: true

        firstname:
            ordering@: fullname
            label: Nome
            type: text
            validate:
                required: true

        lastname:
            ordering@: firstname
            label: Cognome
            type: text
            validate:
                required: true
```
If I misunderstood, I'm sorry :-)

**Comment by david-szabo97** [comment]
I'm not sure what's the proper way to override plugin blueprints.
Since the blueprint is in the blueprints directory of the plugin, I thought this will work:
```yml
extends@:
  type: user/group
  context: plugin://admin-addon-user-manager/blueprints
```

But it doesn't work.

I'm happy to make changes to the plugin if that's the only way, but I'm not sure what's going on under the hood regarding the bluperints.
